ALTER TABLE carts RENAME TO cart;

ALTER TABLE cart
    ADD COLUMN session_id VARCHAR(255),
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP;